[package]
name = "gw2orrient"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.13.2", features = ["wayland"] }
# bevy = { git = "https://github.com/bevyengine/bevy.git", tag = "v0.14.0-rc.3", features = ["wayland"] }
bincode = "1.3.3"
crossbeam-channel = "0.5.13"
env_logger = "0.11.3"
mumblelink = { path = "mumblelink" }
marker = { path = "marker" }
mumblelink_reader = "0.3.5"
serde = { version = "1.0.203", features = ["derive"] }
quick-xml = { version = "0.32.0", features = ["serialize"] }
bevy-inspector-egui = "0.24.0"
# bevy_lunex = "0.1.0"
bevy_lunex = { path = "../bevy_lunex/crates/bevy_lunex/" }
# bevy_lunex = { path = "../bevy_lunex/crates/bevy_lunex/", features = ["debug"] }
# bevy_lunex = { git = "https://github.com/purplg/bevy_lunex.git", branch = "feat/scroll-support" }
dirs = "5.0.1"
bevy_mod_billboard = "0.6.0"
bevy_console = "0.11.1"
clap = "4.5.7"

[workspace]
resolver = "2"
members = [
  "mumblelink",
  "marker",
]
