[package]
name = "gw2orrient"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"

orrient_input = { path = "orrient_input" }

# Mumblelink connectivity
orrient_link = { path = "orrient_link" }
mumblelink_reader = "0.3.5"
bincode = "1.3.3"
crossbeam-channel = "0.5.13"

# Marker parsing
dirs = "5.0.1"
quick-xml = { version = "0.32.0", features = ["overlapped-lists"] }
petgraph = "0.6.5"
typed-path = "0.9.0"
zip = "2.1.3"

# https://github.com/bevyengine/bevy/
bevy = { version = "0.14.0", features = ["wayland", "file_watcher"] }

# https://github.com/RichoDemus/bevy-console/
bevy_console = { git = "https://github.com/msklosak/bevy-console", branch = "bevy_014" }
clap = { version = "4.5.10", features = ["derive"] }

# https://github.com/jakobhellermann/bevy-inspector-egui/
# bevy-inspector-egui = "0.24.0"

# https://github.com/kulkalkul/bevy_mod_billboard
bevy_mod_billboard = "0.7.0"

# https://github.com/UmbraLuminosa/sickle_ui
sickle_ui = { rev = "2f2fae98ef745a6ed51fe71e00188fb9f1be733e", git = "https://github.com/UmbraLuminosa/sickle_ui" }
itertools = "0.13.0"
anyhow = "1.0.86"
lazy_static = "1.5.0"

[workspace]
resolver = "2"
members = [
  "orrient_input",
  "orrient_link",
]
