[package]
name = "gw2orrient"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"

# Mumblelink connectivity
orrient_link = { path = "orrient_link" }
mumblelink_reader = "0.3.5"
bincode = "1.3.3"
crossbeam-channel = "0.5.13"

# Marker parsing
orrient_parser = { path = "orrient_parser" }
dirs = "5.0.1"

# https://github.com/bevyengine/bevy/
bevy = { version = "0.13.2", features = ["wayland"] }

# https://github.com/RichoDemus/bevy-console/
bevy_console = "0.11.1"
clap = "4.5.7"

# https://github.com/jakobhellermann/bevy-inspector-egui/
bevy-inspector-egui = "0.24.0"

# https://github.com/kulkalkul/bevy_mod_billboard
bevy_mod_billboard = "0.6.0"

# https://github.com/UmbraLuminosa/sickle_ui
sickle_ui = { rev = "d09e1c98d608fd5ca99b21fad1c15a6321d466b6", git = "https://github.com/UmbraLuminosa/sickle_ui" }
itertools = "0.13.0"

[workspace]
resolver = "2"
members = [
  "orrient_link",
  "orrient_parser",
]
