[package]
name = "gw2orrient"
version = "0.1.0"
edition = "2021"

[dependencies]
env_logger = "0.11.3"
itertools = "0.13.0"
anyhow = "1.0.86"

orrient_api = { path = "orrient_api" }

# A workspace for sharing inputs between the Linux overlay and Windows
# link applications.
orrient_input = { path = "orrient_input" }

### Mumblelink Connectivity ####################################################
orrient_link = { path = "orrient_link" }
mumblelink_reader = "0.3.5"
bincode = "1.3.3"
crossbeam-channel = "0.5.13"

### Marker parsing #############################################################
dirs = "5.0.1"
quick-xml = { version = "0.32.0", features = ["overlapped-lists"] }
petgraph = "0.6.5"
typed-path = "0.9.0"
zip = "2.1.3"

# https://github.com/bevyengine/bevy/
bevy = { version = "0.14.1", features = ["wayland", "file_watcher"] }

### UI #########################################################################
# https://github.com/UmbraLuminosa/sickle_ui
sickle_ui = { rev = "34005a18ae600f09a0f300034e3fc6fd608929ef", git = "https://github.com/UmbraLuminosa/sickle_ui" }
# https://github.com/kulkalkul/bevy_mod_billboard
bevy_mod_billboard = "0.7.0"
# https://github.com/RichoDemus/bevy-console/
bevy_console = { git = "https://github.com/msklosak/bevy-console", branch = "bevy_014" }
# https://github.com/clap-rs/clap
clap = { version = "4.5.10", features = ["derive"] }

[workspace]
resolver = "2"
members = [ "orrient_api",
  "orrient_input",
  "orrient_link",
]

[profile.dev]
opt-level = 1
incremental = true

[profile.dev.package."*"]
opt-level = 3

[dev-dependencies]
lazy_static = "1.5.0"
tempfile = "3.12.0"
