[package]
name = "mumblelink"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
byteorder = "1.5.0"
crossbeam-channel = "0.5.13"
mumblelink_reader = "0.3.5"
rdev = "0.5.3"
serde = { version = "1.0.203", features = ["derive"] }
