[package]
name = "marker"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1.0.203", features = ["derive"] }
quick-xml = { version = "0.32.0", features = ["serialize"] }
nom = "7.1.3"
