[package]
name = "orrient_input"
version.workspace = true
edition.workspace = true

[dependencies]
bevy = { workspace = true, features = ["serialize"] }
smol_str.workspace = true
serde.workspace = true
