[package]
name = "orrient_input"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_app = "0.14.0"
bevy_ecs = "0.14.0"
smol_str = { version = "0.2.2", features = ["serde"] }
bevy_input = { version = "0.14.0", features = ["serialize"] }
serde = "1.0.204"
