[package]
name = "orrient_api"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
gw2lib = "3.0.0"
bevy_async_task = "0.2.0"
reqwest = "0.12.7"
serde = "1.0.210"
serde_json = "1.0.128"
thiserror = "1.0.63"
